# data
dataset_path: './datasets/kspon/train'
output_unit: 'character' # [character, subword, grapheme]
vocab_path: "./Vocabulary/kspon_${trainer.output_unit}/kspon_sentencepiece.model" # subword의 경우 모델 path 
transcripts_path: './Vocabulary/kspon_${trainer.output_unit}/transcripts.txt'

# trainer
epochs: 40
batch_size: 8
learning_rate: 1e-5

save_result_every: 1000
checkpoint_every: 5000
print_every: 10
mode: 'train'
seed: 1004
early_stopping: 30
label_smoothing_value: 0.1

# device
use_cuda: True

# optim
optimizer: "AdamW"   # choice of [Adam, AdamW]
optimizer_b1: 0.9
optimizer_b2: 0.999
optimizer_e: 1e-08
weight_decay: 1e-05

max_grad_norm: 400
warmup_steps: 4000
reduction: 'mean'
