# data
dataset_path: ''
output_unit: 'character' # [character, subword, grapheme]
transcripts_path: './Vocabulary/kspon_${trainer.output_unit}/transcripts.txt'

# trainer
num_epochs: 40
batch_size: 32
save_result_every: 1000
checkpoint_every: 5000
print_every: 10
mode: 'train'
seed: 1004

# device
use_cuda: True

# optim
optimizer: 'adam'
init_lr: 1e-06
final_lr: 1e-07
peak_lr: 1e-04
init_lr_scale: 0.01
final_lr_scale: 0.05
max_grad_norm: 400
warmup_steps: 4000
weight_decay: 1e-05
reduction: 'mean'