dataset_path: "./datasets/kspon/train"
output_unit: "subword"   # [character, subword, grapheme]
save_path: "./Vocabulary/kspon_${preprocess.output_unit}"
preprocess_mode: "phonetic" # [spelling, phonetic]
vocab_size: 5000